git:
  depth: 1

sudo: false

language: node_js
node_js:
  - "5"
  - "4"
  # - "0.12"
  # - "0.10"

script: "npm run $TEST_SUITE"

env:
  - TEST_SUITE=test
  - TEST_SUITE=integration TEST_PRESET=./test/scripts/forgotten-rules.json
  # - TEST_SUITE=integration TEST_PRESET=airbnb,grunt,mdcs
  # - TEST_SUITE=integration TEST_PRESET=crockford,idiomatic,node-style-guide
  # - TEST_SUITE=integration TEST_PRESET=google,jquery,wordpress

matrix:
  include:
    - node_js: 5, env: TEST_SUITE=coveralls
    - node_js: 5, env: TEST_SUITE=lint
    - node_js: 5, env: TEST_SUITE=integration TEST_PRESET=airbnb,grunt,mdcs

cache:
  directories:
  - node_modules

